name: release-image-build

on:
  workflow_dispatch:

jobs:
  release_dashboard_image:
    env:
      working-directory: ./dashboard
    name: Release Dashboard Docker Image
    runs-on: ubuntu-22.04
    steps:

    - name: Error if not a tag
      uses: actions/github-script@v7
      if: ${{ ! startsWith(github.ref, 'refs/tags/') }}
      with:
        script: core.setFailed('This action can only be run on tags')

    - name: Check out code into dashboard directory
      uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Extract tag
      id: tag
      run: echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

    - name: Get revision SHA
      id: vars
      run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"

    - name: Set up Docker
      uses: docker-practice/actions-setup-docker@master

    - name: Log in to Quay.io
      uses: docker/login-action@v2
      with:
        username: mortalhappiness
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push Dashboard image
      uses: docker/build-push-action@v4
      with:
        context: ${{ env.working-directory }}
        file: ${{ env.working-directory }}/Dockerfile
        push: true
        tags: |
          mortalhappiness/kuberay-dashboard:${{ steps.vars.outputs.sha_short }}
          mortalhappiness/kuberay-dashboard:${{ env.tag }}
        labels: |
          GIT_COMMIT=${{ steps.vars.outputs.sha_short }}
        provenance: false
