name: test-ci
on:
  workflow_dispatch:

jobs:
  test-job:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Error if not a tag
        uses: actions/github-script@v7
        if: ${{ ! startsWith(github.ref, 'refs/tags/') }}
        with:
          script: core.setFailed('This action can only be run on tags')
      - name: Extract tag
        id: tag
        run: echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
      - name: Echo tag in Bash
        run: |
          echo "env.tag is ${{ env.tag }}"
          echo "tag is ${tag}"
      - uses: imesense/gha-echo-action@v0.2
        name: Echo tag in action (env.tag)
        with:
          input-string: "${{ env.tag }}"
      - uses: imesense/gha-echo-action@v0.2
        name: Echo tag in action (tag)
        with:
          input-string: "${tag}"
      - name: Echo in GitHub scripts
        uses: actions/github-script@v7
        with:
          script: |
            const tag = process.env.tag;
            const tag1 = '${{ env.tag }}';
            console.log(`tag is ${tag}`);
            console.log(`tag1 is ${tag1}`);
